algoritmo "semnome"
var

N1, N2, N3, N4, M: Real
inicio
Escreval("Calcule sua média e veja se passou de ano")
Escreva("Qual foi sua nota do primeiro bimestre?")
Leia(N1)
Escreva("Qual foi sua nota do segundo bimestre?")
Leia(N2)
Escreva("Qual foi sua nota do terceiro bimestre?")
Leia(N3)
Escreva("Qual foi sua nota do quarto bimestre?")
Leia(N4)
M <- (N1+N2+N3+N4)/4
Escreva("Sua média anual foi" ,M)

fimalgoritmo
